Tons/urls.py
from django.contrib import admin
from django.urls import path, include
import Tons.views
import category.views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', Tons.views.home, name='home'),
    path('<int:user_id>/', Tons.views.home, name='home'),

    path('mypage/<int:user_id>/', category.views.mypage, name='mypage'),

    path('category/', include('category.urls')),
    path('article/', include('article.urls', namespace="article")),
    path('accounts/', include('accounts.urls')),

    # path('cat_detail', base_app.views.category_detail, name='cat_detail'), #추후 url 수정 필요

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name="login"),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('<int:article_id>/', views.detail, name="detail"),
    path('<int:article_id>/summary/', views.summary, name="summary"),
    path('summary_obj/<int:summary_id>/', views.summary_obj, name="summary_obj"),
    path('summary_sbj/<int:summary_id>/', views.summary_sbj, name="summary_sbj"),
    path('<int:article_id>/stars/', views.stars, name="stars"),
]

article/models.py
from django.db import models
from django.utils import timezone
from accounts.models import Profile
from category.models import Category
from easy_thumbnails.fields import ThumbnailerImageField
# Create your models here.

class Article(models.Model):

    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null = True)
    content = models.TextField()
    original = models.TextField()
    stars = models.FloatField(default=0)
    stars_count = models.PositiveIntegerField(default=0)
    photo = models.ImageField(upload_to="media\img", null=True, blank=True)
    thumbnail = ThumbnailerImageField(upload_to='article', blank=True)
    
    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:100]

    class Meta:
        ordering = ['-stars'] 

class Summary(models.Model):
    belongsto_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    belongsto_user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    obj_count = models.PositiveIntegerField(default=0) #객관지수
    sbj_count = models.PositiveIntegerField(default=0)  #주관지수

    def __str__(self):
        return self.content
        
    class Meta:
        get_latest_by = "obj_count"
        ordering = ['-pub_date']
        verbose_name_plural = "Summaries"

article/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from .models import Article, Summary
from accounts.models import Profile

# Create your views here.

def detail(request, article_id):
    article = get_object_or_404(Article, pk = article_id)
    summary_list = Summary.objects.filter(belongsto_article=article)
    other_articles = []
    best_summ_list = dict()

    for other in Article.objects.filter(category=article.category):
        if other != article:
            other_articles.append(other)
        try:
            best_summ_list[other.id] = Summary.objects.filter(belongsto_article=other.id).latest('obj_count')
        except: #요약이 하나도 없을 경우
            best_summ_list[other.id] = '아직 요약이 없습니다!'
    
    context = {
        'article':article,
        'summary_list':summary_list,
        'best_summ_list':best_summ_list,
        'other_articles':other_articles,
    }
    return render(request,"article/article_detail.html", context)

def summary(request, article_id):

    if request.method == "POST":
        summary = Summary()
        summary.belongsto_article = Article.objects.get(id=article_id)
        try:
            user = request.user
            profile = Profile.objects.get(user=user)
            summary.belongsto_user = profile
            summary.content = request.POST['content']
            summary.save()
        except: #유저 로그인 안했을 경우
            return redirect('accounts:login')
        return redirect('article:detail', article_id)
    else:
        try:
            user = request.user
            profile = Profile.objects.get(user=user)
        except: #유저 로그인 안했을 경우
            return redirect('accounts:login')
        return render(request, 'article/summary.html')

def summary_obj(request, summary_id):
    
    summary = Summary.objects.get(id=summary_id)
    try:
        user = request.user
        profile = Profile.objects.get(user=user)
    except: # 유저로그인 안했을경우
        return redirect('accounts:login')

    check_sbj_sum = profile.sbj_sum.filter(id=summary_id)

    if check_sbj_sum.exists():
        profile.sbj_sum.remove(summary)
        profile.obj_sum.add(summary)
        summary.sbj_count -= 1
        summary.obj_count += 1
        summary.save()

    else:
        profile.obj_sum.add(summary)
        summary.obj_count += 1
        summary.save()

    return redirect('article:detail', summary.belongsto_article.id)

def summary_sbj(request, summary_id):
    
    summary = Summary.objects.get(id=summary_id)
    try:
        user = request.user
        profile = Profile.objects.get(user=user)
    except: # 유저로그인 안했을경우
        return redirect('accounts:login')

    check_obj_sum = profile.obj_sum.filter(id=summary_id)

    if check_obj_sum.exists():
        profile.obj_sum.remove(summary)
        profile.sbj_sum.add(summary)
        summary.obj_count -= 1
        summary.sbj_count += 1
        summary.save()
    else:
        profile.sbj_sum.add(summary)
        summary.sbj_count += 1
        summary.save()

    return redirect('article:detail', summary.belongsto_article.id)

def stars(request, article_id):

    try:
        user = request.user
        profile = Profile.objects.get(user=user)

    except: # 유저로그인 안했을경우
        return redirect('accounts:login')

    if request.method == "POST":
        article = get_object_or_404(Article, pk = article_id)
        star_score = int(request.POST.get('star_score'))
        stars = article.stars
        count = article.stars_count
        now_total = stars * count
        count += 1
        article.stars_count = count
        stars = ( now_total + star_score ) / count
        article.stars = round(stars,2)
        article.save()
        return redirect('article:detail', article_id)

    else:
        return render(request, 'article/stars.html')

article/templates/article/article_detail.html
{% extends 'base.html' %}


{% load staticfiles %}
{% load thumbnail %}

{% block title %}
<title>Tons: detail</title>
{% endblock title %}


{% block css %}
<link rel="stylesheet" href="{%static 'css/article_detail.css'%}">
{% endblock css %}

{% block contents %}
    <div class="article_wrapper">
        <div class="article_title">{{article.title}}</div>
        <div class="article_body">
            {% if article.photo %}
                <div class="article_photo">
                    <img src="{{ article.photo.url }}">
                </div>
            {% endif %}
            <div class="article_text">
                <p>{{article.content}}</p>
                <p>{{article.pub_date}}</p>
                <p>{{article.stars}}</p>
                {% if user.is_active %}
                    <a href="{% url 'article:stars' article.id %}">별점 매기기</a>
                {% else %}
                    <a href="{% url 'accounts:login'%}">별점 매기기</a>
                {% endif %}
            </div>
            
        </div>
        <div class="lines">
            <div class="category_text">기사 전문 보기<div class="square"
                    style=" width: 20px;   height: 20px;   background-color: #6f6f6f;"></div>
            </div>
        </div>
    </div>


    <div class="wrapper2">
        <div class="middle_contents_container">
            <div class="category_container">
                <div class="category_title_1"> 톤즈의 기자들이 남긴</div>
                <div class="category_title_1"> 세 줄 요약을 만나보세요.</div>
                <div class="lines">
                    <div class="category_text"> 
                    {% if user.is_active %}
                    <a href="{% url 'article:summary' article.id %}">세 줄 남기기</a>
                    {% else %}
                    <a href="{% url 'accounts:login'%}">세 줄 남기기</a>
                    {% endif %}
                    <div class="square" style=" width: 20px;   height: 20px;   background-color: #6f6f6f;"></div>
                    </div>
                    

                </div>
            </div>


            <ul class="category_article">
            {% for summary in summary_list %}
                <li>
                    <a href="#">
                        <div class="category_article_content">
                            <div class="category_article_textcontainer">
                                <div class="text">
                                    <div class="line_1">
                                        {{summary.content}}
                                    </div>
                                    <!-- <div class="line_1">수 가치를 수 가치를 꽃이 위하여서. 용기가 말이다.
                                    </div>
                                    <div class="line_2">황금시대의 가는 뛰노는 발휘하기 가치를 봄바람이다.
                                    </div>
                                    <div class="line_3"> 천자만홍이 보이는 아름답고 심장의 봄바람이다.
                                    </div> -->
                                    <div class="summary_info">
                                        <p>{{summary.belongsto_user}} <span>{{summary.pub_date}}</span></p>
                                    </div>
                                </div>
                            </div>
                            {% if user.is_authenticated %}
                            <div class="category_article_othercontainer">
                                <div class="littlebox">
                                    <div class="square"
                                        style=" width: 20px;   height: 20px;   background-color: #6f6f6f;"></div>
                                    <div class="goodbad">
                                        <a href="{% url 'article:summary_obj' summary.id %}">
                                        {% if article in user.profile.obj_sum.all %}
                                            취소
                                        {% else %}
                                            좋아요
                                        {% endif %}
                                        </a>
                                    <span class="num">{{summary.obj_count}}</span> </div>
                                </div>
                                <div class="littlebox">
                                    <div class="vs">VS</div>
                                </div>
                                <div class="littlebox">
                                    <div class="square"
                                        style=" width: 20px;   height: 20px;   background-color: #6f6f6f;"></div>
                                    <div class="goodbad">
                                        <a href="{% url 'article:summary_sbj' summary.id %}">
                                        {% if article in user.profile.sbj_sum.all %}
                                            취소
                                        {% else %}
                                            글쎄요
                                        {% endif %}
                                        </a>    
                                    <span class="num">{{summary.sbj_count}}</span></div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!--    같은 기사 다른 요약-->



    <div class="card_container_wrapper">
        <div class="headline">
            <div class="headline_2">{{article.category.name}} 관련 다른 기사는 어떠세요?</div>
        </div>
        <div class="card_container">
            <ul>
                {% for other in other_articles%}
                <li>
                    <a href="{% url 'article:detail' other.id%}">
                        <div class="image_container">
                        {% if other.thumbnail %}
                            <img src="{% thumbnail other.thumbnail 472x290 crop %}" alt="">
                            {% else %}
                           <img src="{% static 'img/test_image.png' %}" alt="">
                            {% endif %}
                            <div class="article_title">
                                {{other.title}}
                            </div>
                        </div>
                        <div class="text">
                            {% for key, value in best_summ_list.items %}
                            {% if key == other.id %}
                            <div class="line_1">{{ value }}</div>
                            {% endif %}
                            {% endfor %}
                            {% comment %} <div class="line_1">수 가치를 수 가치를 꽃이 위하여서. 용기가 말이다.
                            </div>
                            <div class="line_2">황금시대의 가는 뛰노는 발휘하기 가치를 봄바람이다.
                            </div>
                            <div class="line_3"> 천자만홍이 보이는 아름답고 심장의 봄바람이다.
                            </div> {% endcomment %}
                        </div>
                        <div id="writer">
                            <span class="by">by</span>
                            <span class="name">{{other.writer}}</span></div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!--같은 주제 다른 기사-->

{% endblock contents %}

article/templates/article/star.html
<form method="POST" action="{% url 'signup'%}">

    {% csrf_token %}
    <select name="star_score" id="star_score">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
    </select>
    <input type="submit" value="">
</form>

article/templates/article/stars.html
<form method="POST" action="">

    {% csrf_token %}
    <select name="star_score" id="star_score">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
    </select>
    <input type="submit" value="submit">

</form>

article/templates/article/summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>summary</title>
    <link href="https://fonts.googleapis.com/css?family=DM+Serif+Display:400,400i|Noto+Sans+KR|Song+Myung&display=swap&subset=korean" rel="stylesheet">
    <style>
        body {
            margin: 0;
            overflow-x: hidden;
            background: rgba(244, 244, 244, 0.80);
        }

        ul {
            padding: 0;
            margin: 0;
        }

        li {
            list-style: none;
        }

        a {
            text-decoration: none;
            color: #000000;
        }

        .sum_wrap {
            width: 487px;
            position: absolute;
            top: 10%;
            left: 50%;
            transform: translateX(-50%);
        }

        .sum_title {
            opacity: 0.87;
            font-family: 'Song Myung', sans-serif;
            font-size: 44px;
            color: #000000;
            letter-spacing: 0;
            padding-bottom: 24px;
        }

        .sum_sub_title {
            opacity: 0.6;
            font-family: 'Noto Sans KR', sans-serif;
            font-size: 18px;
            color: #000000;
            letter-spacing: 0;
            padding-bottom: 12px;
        }

        .sum_input {
            width: 100%-32;
            height: 571px;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: white;
        }

        .sum_input textarea {
            width: 423px;
            height: 507px;
            opacity: 0.6;
            font-family: 'Noto Sans KR',sans-serif;
            font-size: 18px;
            color: #000000;
            letter-spacing: 0;
        }

        .sum_submit {
            width: 100%;
            height: 92px;
            background-color: #1D1D1D;
            display: flex;
            justify-content: center;
            align-items: center;

            font-family: 'Noto Sans KR', sans-serif;
            font-weight: bold;
            font-size: 24px;
            color: #FFFFFF;
            letter-spacing: 0;

            margin-top: 32px;
        }
    </style>
</head>

<body>
    <div class="sum_wrap">
        <ul>
            <li class="sum_title">당신의 기사를 작성하세요.</li>
            <li class="sum_sub_title">당신의 3줄 요약을 톤즈가 도와드립니다.</li>
            <li class="sum_input"><textarea name="content" id="" cols="30" rows="10"></textarea></li>
            <li class="sum_submit">완료</li>
        </ul>

    </div>
</body></html>