Tons/urls.py
from django.contrib import admin
from django.urls import path, include
import Tons.views
import category.views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', Tons.views.home, name='home'),
    path('<int:user_id>/', Tons.views.home, name='home'),

    path('mypage/<int:user_id>/', category.views.mypage, name='mypage'),

    path('category/', include('category.urls')),
    path('article/', include('article.urls', namespace="article")),
    path('accounts/', include('accounts.urls')),

    # path('cat_detail', base_app.views.category_detail, name='cat_detail'), #추후 url 수정 필요

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name="login"),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('<int:article_id>/', views.detail, name="detail"),
    path('<int:article_id>/summary/', views.summary, name="summary"),
    path('summary_obj/<int:summary_id>/', views.summary_obj, name="summary_obj"),
    path('summary_sbj/<int:summary_id>/', views.summary_sbj, name="summary_sbj"),
    path('<int:article_id>/stars/', views.stars, name="stars"),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'

urlpatterns = [
    path('<int:category_id>/', views.cat_detail, name="cat_detail"),
    path('<int:user_id>/<int:category_id>/', views.cat_add, name="cat_add"),
    path('<int:user_id>/<int:category_id>/r', views.cat_remove, name="cat_remove"),
]

Tons/views.py
from django.shortcuts import render, redirect
from accounts.models import Profile
from article.models import Article, Summary
from category.models import Category
from django.contrib.auth.models import User

def home(request, user_id = None):

    # from django.template.defaulttags import register
    # @register.filter
    # def get_item(dictionary, key):
    #     return dictionary.get(key)

    top10_article = Article.objects.order_by('-stars')[:10]
    top10_best_summ_list = dict()
    best_summ_list = dict()
    
    for article in top10_article:
        try:
            top10_best_summ_list[article.id] = Summary.objects.filter(belongsto_article=article.id).latest('obj_count')
        except: #요약이 하나도 없을 경우
            top10_best_summ_list[article.id] = '아직 요약이 없습니다!'

    if user_id: #유저가 선택한 카테고리
        user = User.objects.get(id = user_id)
        try:
            profile = Profile.objects.get(user = user)
        except: #어드민계정예외
            user_id = None
            return redirect('home')
        
        user_cat_list = profile.category.all()
        user_category = dict()
        
        for category in user_cat_list:
            try:
                article = Article.objects.filter(category=category.id).latest('stars')
                user_category[category] = article
                try:
                    best_summ_list[article.id] = Summary.objects.filter(belongsto_article=article.id).latest('obj_count')
                except: #요약이 하나도 없을 경우
                    best_summ_list[article.id] = '아직 요약이 없습니다!'
            except: # 하나도 없을 경우
                best_summ_list = None
                user_category[category] = '기사가 없습니다.'            
        return render(request, 'home.html', {'top10_article' : top10_article,'article_by_category': user_category, 'best_summ_list':best_summ_list, 'top10_best_summ_list':top10_best_summ_list})

    else: #최신 기사가 올라온 카테고리 3개
        new_article = Article.objects.order_by('-pub_date')[:5]
        rand_category_list = []
        
        for article in new_article:
            rand_category_list.append(article.category)

        rand_category = dict()
        for category in rand_category_list:
            try:
                article = Article.objects.filter(category=category.id).latest('stars')
                rand_category[category] =article
                try:
                    best_summ_list[article.id] = Summary.objects.filter(belongsto_article=article.id).latest('obj_count')
                except: #요약이 하나도 없을 경우
                    best_summ_list[article.id] = '아직 요약이 없습니다!'
            except: # 하나도 없을 경우
                best_summ_list = None
                rand_category[category] = '기사가 없습니다.'

        return render(request, 'home.html', {'top10_article' : top10_article,'article_by_category': rand_category, 'best_summ_list':best_summ_list, 'top10_best_summ_list':top10_best_summ_list})



    
    

Tons/templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block title %}
    {% endblock title %}

    <link href="https://fonts.googleapis.com/css?family=DM+Serif+Display:400,400i|Noto+Sans+KR|Song+Myung&display=swap&subset=korean" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{%static 'css/header.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/footer.css'%}">
    
    
    {% block css %}
    {% endblock css %}

</head>

<body>

    <header>
        <div class="header_container">
            <div class="header_container_nav">
                <div class="logo_tons"></div>

                <nav>
                    <ul>
                        <li class="logo_pen"></li>
                        {% if user.is_active %}
                        <li><a href="{% url 'accounts:logout' %}">나가기</a>
                        </li>
                        <li><a href="{% url 'mypage' user.id %}">마이페이지</a></li>
                        <li><a href="{% url 'home' user.id %}">홈&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp&nbsp&nbsp</a></li>
                        <li>{{user.username}}님 환영합니다!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp&nbsp&nbsp</li>
                        {% else %}
                        <li><a href="{% url 'accounts:signup' %}">시작하기</a></li>
                        <li><a href="{% url 'accounts:login'%}">로그인하기</a></li>
                        <li><a href="{% url 'home' %}">홈&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp&nbsp&nbsp</a></li>
                        {% endif %}
                    </ul>
                </nav>

            </div>
        </div>
    </header>

    <div class="body">
        {% block contents %}
        
        {% endblock contents %}
    </div>


    <footer>
        <div class="footer">
            <div class="foot_container_1">
            
                        <div class="foot_info_1">
                            <div id="bold">안내</div>
                            <div class="normal">공지사항</div>
                            <div class="normal">자주 묻는 질문</div>
                            <div class="normal">계정 일시 잠금</div>
                            <div class="normal">공고</div>
                        </div>
                    
                        <div class="foot_info_2">
                            <div id="bold">기타문의</div>
                            <div class="normal">비즈니스 제휴</div>
                            <div class="normal">마케팅 PR</div>
                        </div>
                    
                        <div class="foot_info_3">
                            <div id="bold">고객센터</div>
                            <div class="normal">전화:<span>1234-5678</span></div>
                            <div class="normal">이메일 :<span>abcd1234@likelion.org</span></div>
                            <div class="normal">카카오톡 :<span>@Tons</span> </div>
                        </div>
                 
            </div>
            <div class="foot_container_2">
                <div class="normal">(주)톤즈&nbsp;&nbsp;&nbsp;&nbsp;사업자등록번호 : 123-45-6789</div>
                <div class="normal">서울특별시 동대문구 전농동 서울시립대로 163</div>

                <div class="law_container">
                    <div class="law">

                        <div id="law">서비스 이용약관&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;이용자의 권리 및 유의사항&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;개인정보 처리방침&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;위치기반서비스 이용약관</div>
                    </div>
                    <div class="law_button">
                        <ul>
                            <li>1</li>
                            <li>2</li>
                            <li>3</li>
                            <li>4</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>

Tons/templates/home.html
{% extends 'base.html' %}


{% load staticfiles %}
{% load thumbnail %}
{% block title %}
<title>Tons: homepage</title>
{% endblock title %}


    {% block contents %}
    
   
    <div class="wrapper">
        <div class="upper_contents_container">
            <div class="title_container">
                <div class="title_1 winLoadBefore">
                    톤즈와 함께 기자가 되어보세요.</div>

                <div class="title_2 winLoadBefore">톤즈가 당신에게 전해드리는</div>

                <div class="title_3 winLoadBefore">3 Line Digest of news.</div>
            </div>
        </div>
    </div>
    <!--타이틀-->
   <div class="card_container_wrapper">
        <div class="card_container">
            <ul>
                {% for top10 in top10_article %}
                <li>
                    <a href="{% url 'article:detail' top10.id %}">
                        <div class="image_container">
                            {% if top10.thumbnail %}
                            <div class="img_wrap_1"><img src="{% thumbnail top10.thumbnail 472x290 crop %}" alt=""></div>
                            {% else %}
                            <div class="img_wrap_1"><img src="{% static 'img/test_image.png' %}" alt=""></div>
                            {% endif %}
                            <div class="article_title">
                                {{top10.title}}
                            </div>
                        </div>
                        <div class="text">                        
                            {% for key, value in top10_best_summ_list.items %}
                            {% if key == top10.id %}
                            <div class="line_1">{{ value }}</div>
                            {% endif %}
                            {% endfor %}
                            {% comment %} <div class="line_1">수 가치를 수 가치를 꽃이 위하여서. 용기가 말이다.
                            </div>
                            <div>
                                <div class="line_2 underline">황금시대의 가는 뛰노는 발휘하기 가치를 봄바람이다. 수 가치를 수 가치를 꽃이 위하여서. 용기가 말이다.
                                </div>
                            </div>
                            <div class="line_3"> 천자만홍이 보이는 아름답고 심장의 봄바람이다.
                            </div> {% endcomment %}
                        </div>

                        <div id="writer">
                            <span class="by">by</span>
                            <span class="name">{{top10.writer}}</span></div>
                    </a>
                </li>
                {% endfor %}
            </ul>

        </div>
        <div class="button left">1</div>
        <div class="button right button_before">2</div>
        <div class="page_num_cont page_num_before">
            <ul class="page_num">
                <li class="dot">1</li>
                <li class="dot">2</li>
                <li class="dot">3</li>
                <li class="dot">4</li>
                <li class="dot">5</li>
            </ul>
        </div>
    </div>  
    <!--카드 ui-->

<div class="wrapper">
        <div class="middle_contents_container">
            <div class="category_container category_title_before">
                <div class="category_title_1"> 톤즈의 다양한 기사를 만나보세요.</div>

                <div class="category_title_2"> 3 Line Digest of your category</div>

                <div class="category">
                    <ul>
                    {% for category in article_by_category.keys %}
                        <a href ="{% url 'category:cat_detail' category.id%}"><li>{{category.name}}</li>
                    {% endfor %}
                    </ul>

                </div>
            </div>


            <ul class="category_article">
                {% for category,article in article_by_category.items %}
                {% comment %} 카테고리 별로 별점 높은 기사 하나씩 불러오기 {% endcomment %}
                <li>
                    <a href="{% url 'article:detail' article.id%}">
                        <div class="category_article_content">
                            {% if article.thumbnail %}
                            <div class="img_wrap_2"><img src="{% thumbnail article.thumbnail 130x130 crop %}" alt=""></div>
                            {% else %}
                            <div class="img_wrap_2"><img src="{% static 'img/test_image.png' %}" alt=""></div>
                            {% endif %}
                            <div class="category_article_textcontainer">
                                <div class="catebory_article_title">
                                    {{article.title}}
                                </div>
                                <div class="text">
                                    {% for key, value in best_summ_list.items %}
                                    {% if key == article.id %}
                                    <div class="line_1">{{ value }}</div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="category_article_othercontainer">
                                <div id="category_category">{{category}}</div>
                                <div id="writer">
                                    <span class="by">by</span>
                                    <span class="name">{{article.writer}}</span></div>
                            </div>
                        </div>
                    </a>
                </li>
                {% endfor %}
        
                </li>
            </ul>

        </div>
    </div>

{% comment %}  {% endcomment %}
   
    <!--카드 ui-->
    <!--    카테고리별-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script>
          $(document).ready(function() {
        $('.clue').hover(function () {

               $(this).find('.underline').addClass("hovered"),
                $(this).addClass('hoveredUp'),$(this).removeClass('hoveredDown'),
                   $(this).removeClass('show'), $(this).removeClass('fadein');
           } // 호버된 요소에 클래스를 추가
           ,
           function () {
               $(this).find('.underline').removeClass("hovered"), $(this).removeClass('hoveredUp'),$(this).addClass('hoveredDown'); // 호버된 요소에 클래스를 추가
           });

        })

    </script>
  
   <script>
        $(document).ready(function() {

            var totalLength = $('.card_width').length;
            $('.card_container').css('width', totalLength * 488 + 32);
            //너비 계산//
            console.log(totalLength);

            var cont = $('.card_container')
            var card_position = 2;
            var pageNum = 0;
            console.log(pageNum);

            $('.dot').eq(pageNum).addClass('active');

            $('.left').addClass('opacity');

            function right() {
                if (totalLength > card_position) {
                    cont.animate({
                        marginLeft: '-=976px'
                    }, 800);
                    card_position = 2 + card_position;
                    console.log(card_position);

                    $('.dot').eq(card_position / 2 - 1).addClass('active');

                    $('.dot').eq(card_position / 2 - 2).removeClass('active');

                    if (card_position == totalLength) {
                        $('.right').addClass('opacity');

                    } else if (card_position < totalLength) {
                        $('.right').removeClass('opacity');
                    }

                    if (card_position > 2) {
                        $('.left').removeClass('opacity');

                    } else if (card_position == 2) {
                        $('.left').addClass('opacity');
                    }



                }
            }

            function left() {
                if (card_position > 2) {
                    cont.animate({
                        marginLeft: '+=976px'
                    }, 800);
                    card_position = card_position - 2;
                    console.log(card_position);

                    $('.dot').eq(card_position / 2 - 1).addClass('active');
                    //
                    $('.dot').eq(card_position / 2).removeClass('active');

                    if (card_position == totalLength) {
                        $('.right').addClass('opacity');

                    } else if (card_position < totalLength) {
                        $('.right').removeClass('opacity');
                    }

                    if (card_position > 2) {
                        $('.left').removeClass('opacity');

                    } else if (card_position == 2) {
                        $('.left').addClass('opacity');
                    }

                }
            }


            $('.right').on("click", function() {
                right();
            });


            $('.left').on("click", function() {
                left();
            });

            $('.dot').on("click", function() {
                //                console.log(card_position);
                var dotIndex = $(this).index() * 2;
                //                console.log(dotIndex);

                card_position = dotIndex + 2;
                console.log(card_position);

                var dot = $('.dot').eq(card_position / 2 - 1);

                $('.dot').eq(card_position / 2 - 1).addClass('active');

                $('.dot').not(dot).removeClass('active');

                cont.animate({
                    marginLeft: -dotIndex / 2 * 976
                }, 800);

                if (card_position == totalLength) {
                    $('.right').addClass('opacity');

                } else if (card_position < totalLength) {
                    $('.right').removeClass('opacity');
                }

                if (card_position > 2) {
                    $('.left').removeClass('opacity');

                } else if (card_position == 2) {
                    $('.left').addClass('opacity');
                }

            });


            /* 메인 카드컨테이너 좌우 이동*/



            $(window).scroll(function() {
                $('.fadein').each(function(i) {

                    var bottom_of_object = $(this).offset().top + $(this).outerHeight();
                    var bottom_of_window = $(window).scrollTop() + $(window).height();

                    if (bottom_of_window > bottom_of_object) {

                        $(this).fadeIn(2000, function() {
                            $(this).addClass("show")
                        });
                    }
                });

                $('.nomore1').each(function(i) {

                    var bottom_of_object = $(this).offset().top + $(this).outerHeight();
                    var bottom_of_window = $(window).scrollTop() + $(window).height();

                    if (bottom_of_window > bottom_of_object) {

                        $(this).fadeIn(2000, function() {
                            $(this).addClass("show2")
                        });
                    }
                });

            });


         

            /* 스크롤링 페이드 인 아웃 */

            $('.title_1').addClass('winLoad_1'),
            $('.title_1').removeClass('winLoadBefore');

            $('.title_2').addClass('winLoad_2'), $('.title_2').removeClass('winLoadBefore');

            $('.title_3').addClass('winLoad_3'), $('.title_3').removeClass('winLoadBefore');

            /* title 옆에서 오기 */

            var a = 0;
            var cardCheck = $('.card_check');

            function myLoop() {
                setTimeout(function() {
                    //                    console.log(a);
                    cardCheck.eq(a).addClass('winLoad_test'),
                        cardCheck.eq(a).removeClass('winLoadBefore_2');
                    a++;
                    if (a < totalLength) {
                        myLoop();
                    }
                }, 75)
            }
            myLoop();

            /* 카드 순서대로*/
            
            $('.page_num_cont').addClass('page_num_load'),
            $('.page_num_cont').removeClass('page_num_before');
           
            $('.right').addClass('button_load'),
            $('.right').removeClass('button_before');
            
            $('.category_container').addClass('category_title_load'),
            $('.category_container').removeClass('category_title_before');

           
         
        });
    </script>
   


    
    {% endblock contents %}

   

Tons/templates/mypage.html
{% extends 'base.html' %}
{% load staticfiles %}

    {% block title %}
    <title>Tons</title>
    {% endblock title %}

    {% block css %}
    <link rel="stylesheet" href="{%static 'css/mypage.css'%}">
    {% endblock css %}

    {% block contents %}
    <div class="wrapper">
            <div class="mypage_container">
                <div class="mypage_title_1">
                   더 많은 주제를 구독하세요.</div>

                <div class="mypage_title_2">당신이 선택한 톤즈의</div>

                <div class="mypage_title_3">주제.</div>
            </div>
            
            <div class="box_container">
                <ul>
                    {% for category in user_cat_list %}
                    <li><a href="{% url 'category:cat_remove' user.id category.id %}">{{category.name}}</a></li>
                    {% endfor %}
                </ul>
                
            </div>
    </div>
    <!--당신의 주제를 선태하세요 -->
    
    
    <div class="wrapper">
            <div class="offer_container">
                <div class="offer_title_1">
                   이런 주제는 어떠세요.</div>

                <div class="offer_title_2">톤즈가 당신에게 제안합니다.</div>

                <div class="offer_title_3">we offer you more knowledge.</div>
            </div>
            
            <div class="offer_box_container">
                <ul>
                    {% for category in other_cat_list %}
                    <li><a href="{% url 'category:cat_add' user.id category.id %}">{{category.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
    </div>
   
   {% endblock contents %}